version: "3.3"

services:
  dummy_wca_live:
    image: maxidragon/dummy-wca-live:latest
    container_name: dummy-wca-live
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
